### ISSUE TITLE
Not usable with light theme

### ISSUE THREAD

**Issue by keul** [vn-ki/bracket-colorizer#12]
Great add-on, but it's not usable if your atom use a light theme!

![schermata 2019-01-11 alle 09 32 39](https://user-images.githubusercontent.com/284924/51022180-dfbb3d80-1583-11e9-8a51-f82d37f0d40b.png)

It should provide a light mode, or a way to customize colors.

**Comment by UziTech** [comment]
You can change the color in your stylesheet:

  1. Go to File > Stylesheet... (or run "Application: Open Your Stylesheet" command)

  2. Add the following to your stylesheet and change the colors:

		```less
		atom-text-editor.editor {
		  .bracket-colorizer-color0 {
		      color: white;
		  }
		  .bracket-colorizer-color1  {
		      color: lighten(teal, 30);
		    }
		  .bracket-colorizer-color2 {
		      color: yellow;
		    }
		  .bracket-colorizer-color3  {
		      color: lightblue;
		  }
		  .bracket-colorizer-color4  {
		      color: lightgreen;
		  }
		  .bracket-colorizer-color5 {
		      color: violet;
		  }
		  .bracket-colorizer-color6 {
		    color: orange;
		  }
		  .bracket-colorizer-color7 {
		    color: red;
		  }
		  .bracket-colorizer-color8 {
		    color: rgb(249, 98, 98);
		  }
		  .bracket-colorizer-color9 {
		      color: rgb(1, 204, 190);
		  }
		}
		```

**Comment by magicdawn** [comment]
It's there a recommend color preset for light theme?
I'm poor in color choosing. 😕

**Comment by magicdawn** [comment]
my solution

```less
atom-workspace[class*="light"] {
  @colors: lightgreen, red, teal, violet, orange, lightblue;
  .loop (@i) when (@i < length(@colors)) {
    .bracket-colorizer-color@{i} {
      color: extract(@colors, @i + 1);
    }
    .loop(@i + 1);
  }
  .loop(0);
}
```

![image](https://user-images.githubusercontent.com/4067115/77142407-f380fe80-6aba-11ea-9de8-7e21cf46ffb7.png)

Basic usable now, 😄 
and if the syntax name includes `light`, this style will be applied.
